export const projects = [
    {
        name: "Egeire Color System",
        client: "Egerie",
        description: "Heuristic evaluation and redesign of the Egerie color system.",
        src: "egerie.jpg",
        year: 2024,
        link: "/work/colorsystem",
    },
    {
        name: "Layla",
        client: "Decimal",
        description: "Florist Website and App Design",
        src: "layla.jpg",
        year: 2023,
        link: "https://www.figma.com/board/kgqsnLBSc9rZV0R2wZnZ6y/Layla---UX-Research?node-id=0-1&t=D5y77B7nLt3RXMAy-1",
    },
    {
        name: "YoTrek",
        client: "analogueagency",
        description: "App Design",
        src: "yotrek.jpg",
        year: 2023,
        link: "/work/colorsystem",
    },
    {
        name: "Naraka",
        client: "Wix Playground",
        description: "Branding and Packaging Design",
        src: "naraka.jpg",
        year: 2019,
        link: "https://www.behance.net/gallery/72172873/NARAKA-PROJECT",
    },
    {
        name: "My Human Kit",
        client: "POWELL—STUDIO",
        description: "App Design for People with Disabilities",
        src: "myhumankit.jpg",
        year: 2023,
        link: "https://www.figma.com/design/TX0n0qLGkn6Yvd8ckYpuOp/MHK?node-id=253-18601",
    },
    {
        name: "MFA",
        client: "ET Studio",
        description: "Multi Factor Authentication User Flow Design",
        src: "mfa.jpg",
        year: 2023,
        link: "/work/nda",
    },
    {
        name: "Incubator",
        client: "Ingamana",
        description: "Human Resource Management Web Design",
        src: "incubator.jpg",
        year: 2021,
        link: "/work/nda",
    },
    {
        name: "How I, an intern, inspired my company to focus more on User's Needs",
        client: "Shader Studio",
        description: "A true story",
        src: "realstory.jpg",
        year: 2024,
        link: "/work/nda",
    }
]